# Site settings
title: Rizwan Ahamed
name: Rizwan Ahamed

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://www.rizwan.in
 - title: GitHub
   url: https://github.com/noortas
 - title: LinkedIn
   url: https://au.linkedin.com/in/rizwanahamed

#Any buzzword skills you want to include
skills:
 - Spring MVC
 - Spring Boot
 - AngularJS
 - Microservices
 - Java
 - JPA
 - SQL
 - REST
 - Tech Architecture
 - Hybrid Mobile development
 - Ionic, Cordova


#Work experience is required
roles:
 - title: Senior Technology Specialist
   start: 2016
   end: Ongoing
   employer: Telstra
   description: Telstra is Australia’s leading telecommunications and technology company, offering a full range of communications services and competing in all telecommunications markets. At Telstra, I am working in the SHOP team which manages the website offering of mobile plans and services.
 - title: Senior Consultant
   start: 2016
   end: 2016
   employer: GliNTech (Client - Cochlear)
   description: GLiNTECH is an Australian IT services provider for Enterprise clients. I was working for Cochlear, a medical devices company for ear implants in thier identity migration project from TIM/TAM to Salesforce.
 - title: Senior Consultant
   start: 2015
   end: 2015
   employer: AMP
   description: AMP is a Financial services company in Australia and New Zealand. I was working in thier digital team with thier range of online portals especially in super-annuation and other portfolios.
 - title: Senior Developer/Lead
   start: 2010
   end: 2015
   employer: Pickles Auctions
   description: Pickles Auctions, is an Australian company specialising in auctions and valuations. I was working in the online auctions system.
 - title: Senior Developer
   start: 2009
   end: 2010
   employer: Yum Brands!
   description: A Fortune 500 corporation, Yum operates the licensed brands Taco Bell, KFC, Pizza Hut, and WingStreet worldwide. I was working on thier online franchisee system.
 - title: Senior Consultant
   start: 2008
   end: 2009
   employer: TCS Australia (Client - Woolworths)
   description: Tata Consultancy Services’ is an IT services, consulting and business solutions to global businesses worldwide. The client I was working was for Woolworths for thier multi-million vendor management portal.

#Education is required
education:
 - level: Bachelor of Engineering
   date: 1997
   subject: Electronics & Communication Engineering
   school: Bharathiar University

#List of interesting Github repo/projects to include - optional
github:
 - noortas/bluetooth
 - noortas/Beacon
 - noortas/houndBeaconScanner git status

#Mobile apps section is optional
 apps:
  - name: MakeMyHajj
    platform: Android
    url: https://play.google.com/apps/testing/com.ionicframework.makemyhajj625561
    description: A pilgrims app -still in very early stages in development


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring Boot, Microservices technology Architecture. <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework . I have worked with client side technology, having used AngularJS,jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management, agile practices, sprints and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/Parse. <br/><br/>
